name: Job_inputs_workflow
on:
  workflow_dispatch:
    inputs:
      Operation:
        description: "Choose the operation to be performed"
        type: choice
        required: true
        default: Addition
        options:
          - Addition
          - Subtraction
          - Multiplication
          - Division
            
jobs:
#if else on job level
    Addition:
       if: ${{ github.event.inputs.operation == 'Addition' }}
       runs-on: ubuntu-latest
       outputs:
         result: ${{steps.add.outputs.result}}
       steps:
        - name: Addition
          id: add
          run: |
               a=10
               b=5
               c=$((a+b))
               echo "result=$c" >> "$GITHUB_OUTPUT"
               
    Final_Operation:
      needs: Addition
      runs-on: ubuntu-latest
      steps:
       - name: Addition of 3 to final result
         run: echo "Final answer is $((${{needs.Addition.outputs.result}}+3))"
               
          
      
